---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-schema
  namespace: ecommerce
data:
  schema.sql: |
    CREATE TABLE IF NOT EXISTS orders (
      id SERIAL PRIMARY KEY,
      item VARCHAR(100),
      qty INT,
      address TEXT,
      seller VARCHAR(100) DEFAULT 'Flipkart'
    );
