---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: ecommerce
type: Opaque
data:
  POSTGRES_DB: ZWNvbW1lcmNl   # base64 encoded
  POSTGRES_USER: ZWNvbW1lcmNl
  POSTGRES_PASSWORD: c2VjcmV0
