apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: registry.gitlab.com/<your-username>/<project>/ui:latest
          ports:
            - containerPort: 80
          env:
            - name: MIDDLEWARE_URL
              value: "http://middleware-service:5000"
---
apiVersion: v1
kind: Service
metadata:
  name: ui-service
  namespace: my-app
spec:
  type: LoadBalancer
  selector:
    app: ui
  ports:
    - port: 80
      targetPort: 80
